# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Smart Parent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Smart Parent
pod 'Alamofire', '~> 4.0'
pod 'MBCalendarKit'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SwiftyJSON'
pod 'Charts/Realm'
pod 'FontAwesome.swift'
pod 'JTAppleCalendar', '~> 6.0'
  target 'E-Smart ParentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-Smart ParentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
